<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Dominican Republic', 'code' =>	'DO'],
            ['name' => 'Guatemala', 'code' =>	'GT'],
            ['name' => 'Russia', 'code' =>	'RU'],
            ['name' => 'Azerbaijan', 'code' =>	'AZ'],
            ['name' => 'Moldova', 'code' =>	'MD'],
            ['name' => 'Kenya', 'code' =>	'KE'],
            ['name' => 'Tanzania', 'code' =>	'TZ'],
            ['name' => 'United Arab Emirates', 'code' =>	'AE'],
            ['name' => 'Iraq', 'code' =>	'IQ'],
            ['name' => 'Philippines', 'code' =>	'PH'],
            ['name' => 'Albania', 'code' =>	'AL'],
            ['name' => 'Chile', 'code' =>	'CL'],
            ['name' => 'Peru', 'code' =>	'PE'],
            ['name' => 'Ecuador', 'code' =>	'EC'],
            ['name' => 'Uruguay', 'code' =>	'UY'],
            ['name' => 'Bolivia', 'code' =>	'BO'],
            ['name' => 'El Salvador', 'code' =>	'SV'],
            ['name' => 'Nicaragua', 'code' =>	'NI'],
            ['name' => 'Jamaica', 'code' =>	'JM'],
            ['name' => 'Ukraine', 'code' =>	'UA'],
            ['name' => 'Nigeria', 'code' =>	'NG'],
            ['name' => 'South Africa', 'code' =>	'ZA'],
            ['name' => 'Algeria', 'code' =>	'DZ'],
            ['name' => 'Morocco', 'code' =>	'MA'],
            ['name' => 'Ethiopia', 'code' =>	'ET'],
            ['name' => 'Ghana', 'code' =>	'GH'],
            ['name' => 'Ivory Coast', 'code' =>	'CI'],
            ['name' => 'Rwanda', 'code' =>	'RW'],
            ['name' => 'Saudi Arabia', 'code' =>	'SA'],
            ['name' => 'Kuwait', 'code' =>	'KW'],
            ['name' => 'Oman', 'code' =>	'OM'],
            ['name' => 'Lebanon', 'code' =>	'LB'],
            ['name' => 'Yemen', 'code' =>	'YE'],
            ['name' => 'Sri Lanka', 'code' =>	'LK'],
            ['name' => 'Nepal', 'code' =>	'NP'],
            ['name' => 'Serbia', 'code' =>	'RS'],
            ['name' => 'Montenegro', 'code' =>	'ME'],
            ['name' => 'USA', 'code' =>	'US'],
            ['name' => 'China', 'code' =>	'CN'],
            ['name' => 'India', 'code' =>	'IN'],
            ['name' => 'Japan', 'code' =>	'JP'],
            ['name' => 'Germany', 'code' =>	'DE'],
            ['name' => 'United Kingdom', 'code' =>	'UK'],
            ['name' => 'France', 'code' =>	'FR'],
            ['name' => 'Brazil', 'code' =>	'BR'],
            ['name' => 'Italy', 'code' =>	'IT'],
            ['name' => 'Indonesia', 'code' =>	'ID'],
            ['name' => 'Mexico', 'code' =>	'MX'],
            ['name' => 'South Korea', 'code' =>	'KR'],
            ['name' => 'Canada', 'code' =>	'CA'],
            ['name' => 'Spain', 'code' =>	'ES'],
            ['name' => 'Australia', 'code' =>	'AU'],
            ['name' => 'Turkey', 'code' =>	'TR'],
            ['name' => 'Iran', 'code' =>	'IR'],
            ['name' => 'Taiwan', 'code' =>	'TW'],
            ['name' => 'Netherlands', 'code' =>	'NL'],
            ['name' => 'Argentina', 'code' =>	'AR'],
            ['name' => 'Thailand', 'code' =>	'TH'],
            ['name' => 'Poland', 'code' =>	'PL'],
            ['name' => 'Egypt', 'code' =>	'EG'],
            ['name' => 'Pakistan', 'code' =>	'PK'],
            ['name' => 'Switzerland', 'code' =>	'CH'],
            ['name' => 'Malaysia', 'code' =>	'MY'],
            ['name' => 'Sweden', 'code' =>	'SE'],
            ['name' => 'Colombia', 'code' =>	'CO'],
            ['name' => 'Belgium', 'code' =>	'BE'],
            ['name' => 'Bangladesh', 'code' =>	'BD'],
            ['name' => 'Austria', 'code' =>	'AT'],
            ['name' => 'Singapore', 'code' =>	'SG'],
            ['name' => 'Venezuela', 'code' =>	'VE'],
            ['name' => 'Norway', 'code' =>	'NO'],
            ['name' => 'Vietnam', 'code' =>	'VN'],
            ['name' => 'Hong Kong', 'code' =>	'HK'],
            ['name' => 'Kazakhstan', 'code' =>	'KZ'],
            ['name' => 'Romania', 'code' =>	'RO'],
            ['name' => 'Israel', 'code' =>	'IL'],
            ['name' => 'Denmark', 'code' =>	'DK'],
            ['name' => 'Czech Republic', 'code' =>	'CZ'],
            ['name' => 'Qatar', 'code' =>	'QA'],
            ['name' => 'Ireland', 'code' =>	'IE'],
            ['name' => 'Portugal', 'code' =>	'PT'],
            ['name' => 'Greece', 'code' =>	'GR'],
            ['name' => 'Finland', 'code' =>	'FI'],
            ['name' => 'Hungary', 'code' =>	'HU'],
            ['name' => 'Myanmar', 'code' =>	'MM'],
            ['name' => 'New Zealand', 'code' =>	'NZ'],
            ['name' => 'Angola', 'code' =>	'AO'],
            ['name' => 'Uzbekistan', 'code' =>	'UZ'],
            ['name' => 'Slovakia', 'code' =>	'SK'],
            ['name' => 'Belarus', 'code' =>	'BY'],
            ['name' => 'Sudan (stal2 state)', 'code' =>	'SD'],
            ['name' => 'Puerto-Rico', 'code' =>	'PR'],
            ['name' => 'Bulgaria', 'code' =>	'BG'],
            ['name' => 'Tunisia', 'code' =>	'TN'],
            ['name' => 'Cuba', 'code' =>	'CU'],
            ['name' => 'Croatia', 'code' =>	'HR'],
            ['name' => 'Turkmenistan', 'code' =>	'TM'],
            ['name' => 'Libya', 'code' =>	'LY'],
            ['name' => 'Panama', 'code' =>	'PA'],
            ['name' => 'Lithuania', 'code' =>	'LT'],
            ['name' => 'Costa Rica', 'code' =>	'CR'],
            ['name' => 'Luxembourg', 'code' =>	'LU'],
            ['name' => 'Jordan', 'code' =>	'JO'],
            ['name' => 'Slovenia', 'code' =>	'SI'],
            ['name' => 'Uganda', 'code' =>	'UG'],
            ['name' => 'Cameroon', 'code' =>	'CM'],
            ['name' => 'Bahrain', 'code' =>	'BH'],
            ['name' => 'Democratic Republic of the Congo', 'code' =>	'CD'],
            ['name' => 'Macau', 'code' =>	'MO'],
            ['name' => 'Paraguay', 'code' =>	'PY'],
            ['name' => 'Zambia', 'code' =>	'ZM'],
            ['name' => 'Afghanistan', 'code' =>	'AF'],
            ['name' => 'Latvia', 'code' =>	'LV'],
            ['name' => 'North Korea', 'code' =>	'KP'],
            ['name' => 'Trinidad and Tobago', 'code' =>	'TT'],
            ['name' => 'Cambodia', 'code' =>	'KH'],
            ['name' => 'Syria', 'code' =>	'SY'],
            ['name' => 'Estonia', 'code' =>	'EE'],
            ['name' => 'South Sudan', 'code' =>	'SS'],
            ['name' => 'Honduras', 'code' =>	'HN'],
            ['name' => 'Bosnia and Herz-a', 'code' =>	'BA'],
            ['name' => 'Gabon', 'code' =>	'GA'],
            ['name' => 'Senegal', 'code' =>	'SN'],
            ['name' => 'Georgia', 'code' =>	'GE'],
            ['name' => 'Cyprus', 'code' =>	'CY'],
            ['name' => 'Brunei', 'code' =>	'BN'],
            ['name' => 'Botswana', 'code' =>	'BW'],
            ['name' => 'Mozambique', 'code' =>	'MZ'],
            ['name' => 'Laos', 'code' =>	'LA'],
            ['name' => 'Mongolia', 'code' =>	'MN'],
            ['name' => 'Mali', 'code' =>	'ML'],
            ['name' => 'Madagascar', 'code' =>	'MG'],
            ['name' => 'Somalia', 'code' =>	'SO'],
            ['name' => 'Chad', 'code' =>	'TD'],
            ['name' => 'Burkina Faso', 'code' =>	'BF'],
            ['name' => 'Congo', 'code' =>	'CG'],
            ['name' => 'Zimbabwe', 'code' =>	'ZW'],
            ['name' => 'Equator Nye Guinea', 'code' =>	'GQ'],
            ['name' => 'Macedonia', 'code' =>	'MK'],
            ['name' => 'Namibia', 'code' =>	'NA'],
            ['name' => 'Papua New Guinea', 'code' =>	'PG'],
            ['name' => 'Mauritius', 'code' =>	'MU'],
            ['name' => 'Armenia', 'code' =>	'AM'],
            ['name' => 'Tajikistan', 'code' =>	'TJ'],
            ['name' => 'Iceland', 'code' =>	'IS'],
            ['name' => 'Benin', 'code' =>	'BJ'],
            ['name' => 'Kyrgyzstan', 'code' =>	'KG'],
            ['name' => 'Haiti', 'code' =>	'HT'],
            ['name' => 'Niger', 'code' =>	'NE'],
            ['name' => 'Malawi', 'code' =>	'MW'],
            ['name' => 'Malta', 'code' =>	'MT'],
            ['name' => 'Guinea', 'code' =>	'GN'],
            ['name' => 'Mauritania', 'code' =>	'MR'],
            ['name' => 'Bahamas islands', 'code' =>	'BS'],
            ['name' => 'Togo', 'code' =>	'TG'],
            ['name' => 'Swaziland', 'code' =>	'SZ'],
            ['name' => 'Kurdistan', 'code' =>	'LI'],
            ['name' => 'Sierra Leone', 'code' =>	'SL'],
            ['name' => 'Surinam', 'code' =>	'SR'],
            ['name' => 'Eritrea', 'code' =>	'ER'],
            ['name' => 'Fiji', 'code' =>	'FJ'],
            ['name' => 'East Timor', 'code' =>	'TL'],
            ['name' => 'Burundi', 'code' =>	'BI'],
            ['name' => 'Barbados', 'code' =>	'BB'],
            ['name' => 'Guyana', 'code' =>	'GY'],
            ['name' => 'Butane', 'code' =>	'BT'],
            ['name' => 'Maldives', 'code' =>	'MV'],
            ['name' => 'Lesotho', 'code' =>	'LS'],
            ['name' => 'Liberia', 'code' =>	'LR'],
            ['name' => 'Cape Verde', 'code' =>	'CV'],
            ['name' => 'Palestine', 'code' =>	'PS'],
            ['name' => 'CAR', 'code' =>	'CF'],
            ['name' => 'Belize', 'code' =>	'BZ'],
            ['name' => 'Djibouti', 'code' =>	'DJ'],
            ['name' => 'Gambia', 'code' =>	'GM'],
            ['name' => 'Seychelles', 'code' =>	'SC'],
            ['name' => 'Guinea-Bissau', 'code' =>	'GW'],
            ['name' => 'San Marino', 'code' =>	'SM'],
            ['name' => 'Saint Lucia', 'code' =>	'LC'],
            ['name' => 'Antigua and Barbuda', 'code' =>	'AG'],
            ['name' => 'Grenada', 'code' =>	'GD'],
            ['name' => 'Solomon islands', 'code' =>	'SB'],
            ['name' => 'West Sahara', 'code' =>	'EH'],
            ['name' => 'Saint Kitts and Nevis', 'code' =>	'KN'],
            ['name' => 'Vc', 'code' =>	'VC'],
            ['name' => 'Comoros', 'code' =>	'KM'],
            ['name' => 'Samoa', 'code' =>	'WS'],
            ['name' => 'Vanuatu', 'code' =>	'VU'],
            ['name' => 'Dominica', 'code' =>	'DM'],
            ['name' => 'Sao Tome and Principe', 'code' =>	'ST'],
            ['name' => 'Tonga', 'code' =>	'TO'],
            ['name' => 'Kiribati', 'code' =>	'KI'],
            ['name' => 'Tuvalu', 'code' =>	'TV'],
            ['name' => 'Gaza Strip', 'code' =>	'MQ'],
            ['name' => 'West Coast Jordan River', 'code' =>	'CK'],
            ['name' => 'Jersey Island', 'code' =>	'JE'],
            ['name' => 'French Polynesia', 'code' =>	'PF'],
            ['name' => 'Bermudas', 'code' =>	'BM'],
            ['name' => 'New Caledonia', 'code' =>	'NC'],
            ['name' => 'Wasps Antilles Islands', 'code' =>	'RE'],
            ['name' => 'Andorra', 'code' =>	'AD'],
            ['name' => 'Guernsey Island', 'code' =>	'GG'],
            ['name' => 'Isle Of Man', 'code' =>	'IM'],
            ['name' => 'Guam', 'code' =>	'GU'],
            ['name' => 'Aruba', 'code' =>	'AW'],
            ['name' => 'Cayman Islands', 'code' =>	'KY'],
            ['name' => 'Liechtenstein', 'code' =>	'FM'],
            ['name' => 'Monaco', 'code' =>	'MC'],
            ['name' => 'The Holy See', 'code' =>	'TC'],
            ['name' => 'Zaire', 'code' =>	'SX'],
            ['name' => 'Nauru', 'code' =>	'NR'],
            ['name' => 'Mayotte', 'code' =>	'YT'],
            ['name' => 'Faroe islands', 'code' =>	'FO'],
            ['name' => 'Gibraltar', 'code' =>	'GI'],
            ['name' => 'Greenland', 'code' =>	'GL'],
            ['name' => 'Netherlands Antilles', 'code' =>	'CW'],
            ['name' => 'Tokelau', 'code' =>	'TK'],
            ['name' => 'Marshall Islands', 'code' =>	'MH'],
            ['name' => 'British Virgin Islands', 'code' =>	'VG'],
            ['name' => 'United States Minor Outlying Islands', 'code' =>	'GP'],
            ['name' => 'Anguilla', 'code' =>	'AI'],
            ['name' => 'Northern Mariana Islands', 'code' =>	'MP'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' =>	'FK'],
            ['name' => 'The European Union Nes', 'code' =>	'MF'],
            ['name' => 'EU + Dr. E Page', 'code' =>	'EU'],
        ];

        $orderedCountries = collect($countries)->sortBy('name');

        foreach ($orderedCountries as $country) {
            Country::create([
                'name' => $country['name'],
                'code' => $country['code'],
            ]);
        }
    }
}
